# 산학프로젝트
**제조 공정 품질 불량 예측**

## import

In [1]:
import pandas as pd
import numpy as np
import os

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

## 경로설정

In [2]:
os.chdir("data")

## 데이터 불러오기

In [3]:
labeled=pd.read_csv('labeled_data.csv', encoding='utf-8')

In [4]:
labeled.head()

,_id,TimeStamp,PART_FACT_PLAN_DATE,PART_FACT_SERIAL,PART_NAME,EQUIP_CD,EQUIP_NAME,PassOrFail,Reason,Injection_Time,Filling_Time,Plasticizing_Time,Cycle_Time,Clamp_Close_Time,Cushion_Position,Switch_Over_Position,Plasticizing_Position,Clamp_Open_Position,Max_Injection_Speed,Max_Screw_RPM,Average_Screw_RPM,Max_Injection_Pressure,Max_Switch_Over_Pressure,Max_Back_Pressure,Average_Back_Pressure,Barrel_Temperature_1,Barrel_Temperature_2,Barrel_Temperature_3,Barrel_Temperature_4,Barrel_Temperature_5,Barrel_Temperature_6,Barrel_Temperature_7,Hopper_Temperature,Mold_Temperature_1,Mold_Temperature_2,Mold_Temperature_3,Mold_Temperature_4,Mold_Temperature_5,Mold_Temperature_6,Mold_Temperature_7,Mold_Temperature_8,Mold_Temperature_9,Mold_Temperature_10,Mold_Temperature_11,Mold_Temperature_12
0,5f8928bb9c0189cc666ef19b,2020-10-16 04:57:47,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.59,4.47,16.92,59.520000,7.13,653.409973,0.0,68.849998,647.98999,55.400002,30.700001,292.5,141.800003,136.800003,37.400002,59.299999,276.500000,274.700012,274.799988,269.200012,255.000000,229.699997,0.0,66.300003,0.0,0.0,24.799999,27.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,5f8928de9c0189cc666ef20b,2020-10-16 04:58:48,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.60,4.48,16.91,59.580002,7.13,653.409973,0.0,68.839996,647.98999,55.299999,30.799999,292.5,141.800003,136.899994,37.500000,59.299999,276.200012,275.500000,275.299988,270.799988,254.699997,229.500000,0.0,67.199997,0.0,0.0,24.799999,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5f8928df9c0189cc666ef213,2020-10-16 04:58:48,2020-10-16 오전 12:00:00,23,CN7 W/S SIDE MLD'G LH,S14,650톤-우진2호기,Y,NaN,9.60,4.48,16.91,59.580002,7.13,653.409973,0.0,68.839996,647.98999,55.299999,30.799999,292.5,141.800003,136.899994,37.500000,59.299999,276.200012,275.500000,275.299988,270.799988,254.699997,229.500000,0.0,67.199997,0.0,0.0,24.799999,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5f8928f39c0189cc666ef25e,2020-10-16 04:59:48,2020-10-16 오전 12:00:00,23,CN7 W/S SIDE MLD'G LH,S14,650톤-우진2호기,Y,NaN,9.59,4.48,16.91,59.560001,7.13,653.419983,0.0,68.839996,647.98999,55.299999,31.000000,292.5,141.800003,136.800003,37.500000,59.299999,276.500000,275.000000,275.399994,271.100006,254.899994,230.000000,0.0,66.900002,0.0,0.0,25.000000,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5f8928f59c0189cc666ef265,2020-10-16 04:59:48,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.59,4.48,16.91,59.560001,7.13,653.419983,0.0,68.839996,647.98999,55.299999,31.000000,292.5,141.800003,136.800003,37.500000,59.299999,276.500000,275.000000,275.399994,271.100006,254.899994,230.000000,0.0,66.900002,0.0,0.0,25.000000,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## 데이터 전처리

In [5]:
def info_df(df):
    info=pd.DataFrame(
        {
            "Columns": df.columns,
            "Non-Null Count": df.notna().sum().values,
            "Dtype": df.dtypes.values
        }
    )
    return info

In [6]:
info_df(labeled)

                     Columns  Non-Null Count    Dtype
0                        _id            7996      str
1                  TimeStamp            7996      str
2        PART_FACT_PLAN_DATE            7996      str
3           PART_FACT_SERIAL            7996    int64
4                  PART_NAME            7996      str
5                   EQUIP_CD            7996      str
6                 EQUIP_NAME            7996      str
7                 PassOrFail            7996      str
8                     Reason              71      str
9             Injection_Time            7996  float64
10              Filling_Time            7996  float64
11         Plasticizing_Time            7996  float64
12                Cycle_Time            7996  float64
13          Clamp_Close_Time            7996  float64
14          Cushion_Position            7996  float64
15      Switch_Over_Position            7996  float64
16     Plasticizing_Position            7996  float64
17       Clamp_Open_Position            7996  float64
18       Max_Injection_Speed            7996  float64
19             Max_Screw_RPM            7996  float64
20         Average_Screw_RPM            7996  float64
21    Max_Injection_Pressure            7996  float64
22  Max_Switch_Over_Pressure            7996  float64
23         Max_Back_Pressure            7996  float64
24     Average_Back_Pressure            7996  float64
25      Barrel_Temperature_1            7996  float64
26      Barrel_Temperature_2            7996  float64
27      Barrel_Temperature_3            7996  float64
28      Barrel_Temperature_4            7996  float64
29      Barrel_Temperature_5            7996  float64
30      Barrel_Temperature_6            7996  float64
31      Barrel_Temperature_7            7996  float64
32        Hopper_Temperature            7996  float64
33        Mold_Temperature_1            7996  float64
34        Mold_Temperature_2            7996  float64
35        Mold_Temperature_3            7996  float64
36        Mold_Temperature_4            7996  float64
37        Mold_Temperature_5            7996  float64
38        Mold_Temperature_6            7996  float64
39        Mold_Temperature_7            7996  float64
40        Mold_Temperature_8            7996  float64
41        Mold_Temperature_9            7996  float64
42       Mold_Temperature_10            7996  float64
43       Mold_Temperature_11            7996  float64
44       Mold_Temperature_12            7996  float64

### 중복값 제거

In [7]:
labeled.duplicated().sum()

np.int64(2764)

In [8]:
drop_dup=labeled.drop_duplicates(keep='first', ignore_index=True)
drop_dup.shape

(5232, 45)

In [9]:
drop_dup['PART_NAME'].value_counts()

PART_NAME
CN7 W/S SIDE MLD'G RH        1989
CN7 W/S SIDE MLD'G LH        1985
RG3 MOLD'G W/SHLD, LH         628
RG3 MOLD'G W/SHLD, RH         628
SP2 CVR ROOF RACK CTR, RH       1
JX1 W/S SIDE MLD'G RH           1
Name: count, dtype: int64

### CN7, RG3 제외 삭제

In [10]:
# CN7, RG3만 활용
drop_part=drop_dup[drop_dup['PART_NAME'].str.startswith(("CN7", "RG3"))]

In [11]:
drop_part.shape

(5230, 45)

### 불필요한 변수 삭제

In [12]:
drop_part.columns

Index(['_id', 'TimeStamp', 'PART_FACT_PLAN_DATE', 'PART_FACT_SERIAL',
       'PART_NAME', 'EQUIP_CD', 'EQUIP_NAME', 'PassOrFail', 'Reason',
       'Injection_Time', 'Filling_Time', 'Plasticizing_Time', 'Cycle_Time',
       'Clamp_Close_Time', 'Cushion_Position', 'Switch_Over_Position',
       'Plasticizing_Position', 'Clamp_Open_Position', 'Max_Injection_Speed',
       'Max_Screw_RPM', 'Average_Screw_RPM', 'Max_Injection_Pressure',
       'Max_Switch_Over_Pressure', 'Max_Back_Pressure',
       'Average_Back_Pressure', 'Barrel_Temperature_1', 'Barrel_Temperature_2',
       'Barrel_Temperature_3', 'Barrel_Temperature_4', 'Barrel_Temperature_5',
       'Barrel_Temperature_6', 'Barrel_Temperature_7', 'Hopper_Temperature',
       'Mold_Temperature_1', 'Mold_Temperature_2', 'Mold_Temperature_3',
       'Mold_Temperature_4', 'Mold_Temperature_5', 'Mold_Temperature_6',
       'Mold_Temperature_7', 'Mold_Temperature_8', 'Mold_Temperature_9',
       'Mold_Temperature_10', 'Mold_Temperature_11', 'Mold_Temperature_12'],
      dtype='str')

In [13]:
# 불필요한 컬럼 삭제
drop_columns=['Barrel_Temperature_7', 'EQUIP_CD', 'EQUIP_NAME', 'Mold_Temperature_1', 'Mold_Temperature_10', 'Mold_Temperature_11', 'Mold_Temperature_12', 'Mold_Temperature_2',
               'Mold_Temperature_5', 'Mold_Temperature_6', 'Mold_Temperature_7', 'Mold_Temperature_8', 'Mold_Temperature_9', 'PART_FACT_PLAN_DATE', 'PART_FACT_SERIAL',
               'PART_NAME', 'Reason', 'Switch_Over_Position', 'TimeStamp', '_id']

final_df=drop_part.drop(columns=drop_columns)

In [14]:
final_df.shape

(5230, 25)

In [15]:
final_df.head()

,PassOrFail,Injection_Time,Filling_Time,Plasticizing_Time,Cycle_Time,Clamp_Close_Time,Cushion_Position,Plasticizing_Position,Clamp_Open_Position,Max_Injection_Speed,Max_Screw_RPM,Average_Screw_RPM,Max_Injection_Pressure,Max_Switch_Over_Pressure,Max_Back_Pressure,Average_Back_Pressure,Barrel_Temperature_1,Barrel_Temperature_2,Barrel_Temperature_3,Barrel_Temperature_4,Barrel_Temperature_5,Barrel_Temperature_6,Hopper_Temperature,Mold_Temperature_3,Mold_Temperature_4
0,Y,9.59,4.47,16.92,59.520000,7.13,653.409973,68.849998,647.98999,55.400002,30.700001,292.5,141.800003,136.800003,37.400002,59.299999,276.500000,274.700012,274.799988,269.200012,255.000000,229.699997,66.300003,24.799999,27.5
1,Y,9.60,4.48,16.91,59.580002,7.13,653.409973,68.839996,647.98999,55.299999,30.799999,292.5,141.800003,136.899994,37.500000,59.299999,276.200012,275.500000,275.299988,270.799988,254.699997,229.500000,67.199997,24.799999,27.6
2,Y,9.60,4.48,16.91,59.580002,7.13,653.409973,68.839996,647.98999,55.299999,30.799999,292.5,141.800003,136.899994,37.500000,59.299999,276.200012,275.500000,275.299988,270.799988,254.699997,229.500000,67.199997,24.799999,27.6
3,Y,9.59,4.48,16.91,59.560001,7.13,653.419983,68.839996,647.98999,55.299999,31.000000,292.5,141.800003,136.800003,37.500000,59.299999,276.500000,275.000000,275.399994,271.100006,254.899994,230.000000,66.900002,25.000000,27.6
4,Y,9.59,4.48,16.91,59.560001,7.13,653.419983,68.839996,647.98999,55.299999,31.000000,292.5,141.800003,136.800003,37.500000,59.299999,276.500000,275.000000,275.399994,271.100006,254.899994,230.000000,66.900002,25.000000,27.6

### PassOrFail 인코딩

In [16]:
final_df['PassOrFail']=final_df['PassOrFail'].map({'Y':0, 'N':1})
# 양품: 0, 불량: 1

### 데이터 분할

In [17]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(final_df.drop(columns='PassOrFail'), final_df['PassOrFail'], test_size=0.2, stratify=final_df['PassOrFail'], random_state=0)

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(4184, 24) (4184,)
(1046, 24) (1046,)

### 데이터 스케일링

In [18]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

## 모델링

### Base Model

#### Random Forest

In [19]:
from sklearn import set_config
set_config(display='text')

from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(n_estimators=1000, random_state=0)
rf.fit(x_train_scaled, y_train)

RandomForestClassifier(n_estimators=1000, random_state=0)

In [20]:
pred_rf=rf.predict(x_test_scaled)
rf_acc=rf.score(x_test_scaled, y_test)
print(rf_acc)

0.9818355640535373

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred_rf, target_names=['양품', '불량']))

              precision    recall  f1-score   support

          양품       0.99      0.99      0.99      1034
          불량       0.29      0.42      0.34        12

    accuracy                           0.98      1046
   macro avg       0.64      0.70      0.67      1046
weighted avg       0.99      0.98      0.98      1046

**불량 데이터 샘플링 필요**

### SMOTE: Sampling

In [26]:
# 전체데이터의 60%만 샘플링
from imblearn.over_sampling import SMOTE

x_resampled, x_origin, y_resampled, y_origin=train_test_split(final_df.drop(columns='PassOrFail'), final_df['PassOrFail'], stratify=final_df['PassOrFail'], test_size=0.4, random_state=0)
smote=SMOTE(random_state=0)
print("Before")
print(x_resampled.shape, y_resampled.shape)
print(x_origin.shape, y_origin.shape)

x_resampled, y_resampled=smote.fit_resample(x_resampled, y_resampled)
print("After")
print(x_resampled.shape, y_resampled.shape)
print(x_origin.shape, y_origin.shape)

Before
(3138, 24) (3138,)
(2092, 24) (2092,)
After
(6204, 24) (6204,)
(2092, 24) (2092,)

In [27]:
x_resampled.head()

,Injection_Time,Filling_Time,Plasticizing_Time,Cycle_Time,Clamp_Close_Time,Cushion_Position,Plasticizing_Position,Clamp_Open_Position,Max_Injection_Speed,Max_Screw_RPM,Average_Screw_RPM,Max_Injection_Pressure,Max_Switch_Over_Pressure,Max_Back_Pressure,Average_Back_Pressure,Barrel_Temperature_1,Barrel_Temperature_2,Barrel_Temperature_3,Barrel_Temperature_4,Barrel_Temperature_5,Barrel_Temperature_6,Hopper_Temperature,Mold_Temperature_3,Mold_Temperature_4
0,9.51,4.39,16.799999,59.480000,7.12,653.440002,68.250000,647.98999,56.000000,30.600000,29.200001,141.699997,136.000000,37.400002,59.299999,276.399994,275.600006,275.200012,272.000000,254.899994,229.600006,66.699997,21.100000,22.299999
1,1.06,0.94,12.910000,61.779999,6.81,654.250000,53.580002,4.63000,128.300003,31.000000,290.500000,142.699997,116.099998,55.599998,60.400002,286.100006,285.100006,284.500000,274.700012,264.700012,235.000000,66.900002,22.799999,23.900000
2,9.59,4.47,16.639999,59.520000,7.12,653.440002,68.339996,647.98999,55.099998,30.799999,29.200001,142.100006,136.800003,38.000000,59.700001,275.600006,275.299988,274.500000,269.600006,254.899994,229.800003,65.599998,20.400000,22.200001
3,9.52,4.41,16.799999,59.520000,7.12,653.440002,68.260002,647.98999,55.900002,30.500000,29.200001,141.800003,136.199997,37.799999,59.500000,276.299988,274.700012,275.000000,271.000000,254.899994,230.000000,67.400002,20.400000,21.500000
4,9.59,4.47,16.930000,59.520000,7.12,653.409973,68.849998,647.98999,55.400002,30.799999,292.500000,141.800003,137.000000,37.599998,59.400002,275.600006,275.200012,275.000000,270.399994,254.699997,230.300003,66.599998,25.000000,27.700001

#### 데이터 분할

In [28]:
x_re_train, x_re_test, y_re_train, y_re_test=train_test_split(x_resampled, y_resampled, test_size=0.2, stratify=y_resampled, random_state=0)

print(x_re_train.shape, y_re_train.shape)
print(x_re_test.shape, y_re_test.shape)

(4963, 24) (4963,)
(1241, 24) (1241,)

#### 스케일링

In [29]:
scaler=StandardScaler()

x_re_train_scaled=scaler.fit_transform(x_re_train)
x_re_test_scaled=scaler.transform(x_re_test)

In [30]:
# 학습 모델 저장
model_dict={}

#### Random Forest

In [31]:
smote_rf=RandomForestClassifier(n_estimators=1000, random_state=0)
smote_rf.fit(x_re_train_scaled, y_re_train)

RandomForestClassifier(n_estimators=1000, random_state=0)

In [32]:
model_dict['RandomForest']=smote_rf
pred_srf=smote_rf.predict(x_re_test_scaled)
srf_acc=smote_rf.score(x_re_test_scaled, y_re_test)

print(f'Accuracy: {srf_acc}')
print('Classificatino Report')
print(classification_report(y_re_test, pred_srf, target_names=['양품', '불량']))

Accuracy: 0.9935535858178888
Classificatino Report
              precision    recall  f1-score   support

          양품       0.99      1.00      0.99       621
          불량       1.00      0.99      0.99       620

    accuracy                           0.99      1241
   macro avg       0.99      0.99      0.99      1241
weighted avg       0.99      0.99      0.99      1241

#### Bagging

In [33]:
from sklearn.ensemble import BaggingClassifier

smote_bag=BaggingClassifier(n_estimators=1000, random_state=0)
smote_bag.fit(x_re_train_scaled, y_re_train)

BaggingClassifier(n_estimators=1000, random_state=0)

In [34]:
model_dict['Bagging']=smote_bag
pred_sbag=smote_bag.predict(x_re_test_scaled)
sbag_acc=smote_bag.score(x_re_test_scaled, y_re_test)

print(f'Accuracy: {sbag_acc}')
print('Classificatino Report')
print(classification_report(y_re_test, pred_sbag, target_names=['양품', '불량']))

Accuracy: 0.9871071716357775
Classificatino Report
              precision    recall  f1-score   support

          양품       0.99      0.99      0.99       621
          불량       0.99      0.99      0.99       620

    accuracy                           0.99      1241
   macro avg       0.99      0.99      0.99      1241
weighted avg       0.99      0.99      0.99      1241

#### XGBoost

In [35]:
from xgboost import XGBClassifier

smote_xgb=XGBClassifier(n_estimators=1000, random_state=0)
smote_xgb.fit(x_re_train_scaled, y_re_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=1000,
              n_jobs=None, num_parallel_tree=None, ...)

In [36]:
model_dict['XGBoost']=smote_xgb
pred_sxgb=smote_xgb.predict(x_re_test_scaled)
sxgb_acc=smote_xgb.score(x_re_test_scaled, y_re_test)

print(f'Accuracy: {sxgb_acc}')
print('Classificatino Report')
print(classification_report(y_re_test, pred_sxgb, target_names=['양품', '불량']))

Accuracy: 0.9959709911361805
Classificatino Report
              precision    recall  f1-score   support

          양품       0.99      1.00      1.00       621
          불량       1.00      0.99      1.00       620

    accuracy                           1.00      1241
   macro avg       1.00      1.00      1.00      1241
weighted avg       1.00      1.00      1.00      1241

In [37]:
# 저장된 모델 확인
model_dict

{'RandomForest': RandomForestClassifier(n_estimators=1000, random_state=0),
 'Bagging': BaggingClassifier(n_estimators=1000, random_state=0),
 'XGBoost': XGBClassifier(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, device=None, early_stopping_rounds=None,
               enable_categorical=True, eval_metric=None, feature_types=None,
               feature_weights=None, gamma=None, grow_policy=None,
               importance_type=None, interaction_constraints=None,
               learning_rate=None, max_bin=None, max_cat_threshold=None,
               max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
               max_leaves=None, min_child_weight=None, missing=nan,
               monotone_constraints=None, multi_strategy=None, n_estimators=1000,
               n_jobs=None, num_parallel_tree=None, ...)}

### Test
**샘플링하지 않은 40%를 테스트 데이터로 활용**

#### 데이터 전처리

In [38]:
x_origin_scaled=scaler.transform(x_origin)

#### 예측

In [39]:
# 저장한 학습 모델 불러와서 예측
for model in model_dict:
    x_pred=model_dict[model].predict(x_origin_scaled)
    acc=model_dict[model].score(x_origin_scaled, y_origin)
    print("=" * 80)
    print(model)
    print("=" * 80)
    print(f'Accuracy: {acc}')
    print("Classification Report")
    print(classification_report(y_origin, x_pred, target_names=['양품', '불량']))

================================================================================
RandomForest
================================================================================
Accuracy: 0.9851816443594646
Classification Report
              precision    recall  f1-score   support

          양품       0.99      0.99      0.99      2068
          불량       0.35      0.33      0.34        24

    accuracy                           0.99      2092
   macro avg       0.67      0.66      0.67      2092
weighted avg       0.98      0.99      0.99      2092

================================================================================
Bagging
================================================================================
Accuracy: 0.9741873804971319
Classification Report
              precision    recall  f1-score   support

          양품       0.99      0.98      0.99      2068
          불량       0.21      0.46      0.29        24

    accuracy                           0.97      2092
   macro avg       0.60      0.72      0.64      2092
weighted avg       0.98      0.97      0.98      2092

================================================================================
XGBoost
================================================================================
Accuracy: 0.984225621414914
Classification Report
              precision    recall  f1-score   support

          양품       0.99      0.99      0.99      2068
          불량       0.33      0.38      0.35        24

    accuracy                           0.98      2092
   macro avg       0.66      0.68      0.67      2092
weighted avg       0.99      0.98      0.98      2092